---

version: 2.1

jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y build-essential devscripts
      - run: INSTALL_DEPENDENCIES=y ./build.sh
      - persist_to_workspace:
          root: build
          paths:
            - .
      - store_artifacts:
          path: build
          destination: build

  publish:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 26:a8:a9:e5:94:f1:79:13:88:2a:c7:74:2f:c3:06:fd
      - run: apt-get update
      - run: apt-get install -y aptly gnupg1 gpgv1 ca-certificates git
      - run: echo $GPG_KEY | base64 -d | gpg1 --import
      - attach_workspace:
          at: build
      - run: ./create-repo.sh
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan github.com > ~/.ssh/known_hosts
      - run: git config --global user.email "ci@circleci"
      - run: git config --global user.name "CI"
      - run: git checkout gh-pages || git checkout -b gh-pages
      - run: git rm --cached -r .
      - run: gpg1 --armor --export > gpg.key
      - run: echo pyca.deb.opencast.org > CNAME
      - run: git add pyca .circleci gpg.key CNAME
      - run: git commit -m "Create Repository"
      - run: git push --force origin gh-pages

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
